name       : bombermaaan
version    : 2.2.5.2226
release    : 5
source     :
    - https://github.com/bjaraujo/Bombermaaan/archive/refs/tags/v2.2.5.2226.tar.gz : 6152ddab0e324fa1ee7e66a20f1ad16718ff0e762c4cc29b9787ffc7e4238660
homepage   : https://github.com/bjaraujo/Bombermaaan
license    : GPL-3.0-or-later
component  : games.arcade
summary    : Bombermaaan is a clone of the classic Bomberman game
description: |
    Bombermaaan is a clone of the classic Bomberman game.
builddeps  :
    - pkgconfig(SDL_mixer)
    - pkgconfig(sdl)
setup      : |
    cd trunk
    %cmake -DLOAD_RESOURCES_FROM_FILES:BOOL=ON
build      : |
    %make -C trunk
install    : |
    install -Dm00755 trunk/bin/Bombermaaan $installdir/usr/share/Bombermaaan/bombermaaan
    install -dm00755 $installdir/usr/bin
    ln -sv ../share/Bombermaaan/bombermaaan $installdir/usr/bin/bombermaaan
    cp -r trunk/res/{images,sounds} $installdir/usr/share/Bombermaaan
    cp -r trunk/levels $installdir/usr/share/Bombermaaan
    install -Dm00644 installers/bombermaaan.png -t $installdir/usr/share/pixmaps
    install -Dm00644 installers/bombermaaan.desktop -t $installdir/usr/share/applications
