name       : bombermaaan
version    : 2.1.5.2203
release    : 3
source     :
    - https://github.com/bjaraujo/Bombermaaan/archive/v2.1.5.2203.tar.gz : 77e5891046fcb8432ba25088c778bd2c8beeb34bcc58e1aae63ec4d6880b9741
homepage   : https://github.com/bjaraujo/Bombermaaan
license    : GPL-3.0-or-later
component  : games.arcade
summary    : Bombermaaan is a clone of the classic Bomberman game
description: |
    Bombermaaan is a clone of the classic Bomberman game.
builddeps  :
    - pkgconfig(SDL_mixer)
    - pkgconfig(sdl)
setup      : |
    cd trunk
    %cmake -DLOAD_RESOURCES_FROM_FILES:BOOL=ON
build      : |
    %make -C trunk
install    : |
    install -Dm00755 trunk/bin/Bombermaaan $installdir/usr/share/Bombermaaan/bombermaaan
    install -dm00755 $installdir/usr/bin
    ln -sv ../share/Bombermaaan/bombermaaan $installdir/usr/bin/bombermaaan
    cp -r trunk/res/{images,sounds} $installdir/usr/share/Bombermaaan
    cp -r trunk/levels $installdir/usr/share/Bombermaaan
    install -Dm00644 $pkgfiles/bombermaaan.svg -t $installdir/usr/share/pixmaps
    install -Dm00644 $pkgfiles/bombermaaan.desktop -t $installdir/usr/share/applications
