name       : bombermaaan
version    : 1.9.7.2126
release    : 1
source     :
    - https://github.com/bjaraujo/Bombermaaan/archive/v1.9.7.2126.tar.gz : 0003ff8fda29e3314a6831dad791c38697bd77912e89a7900c908ef6cb89fd8a
license    : GPL-3.0-or-later
component  : games.arcade
summary    : Bombermaaan is a clone of the classic Bomberman game.
description: |
    Bombermaaan is a clone of the classic Bomberman game.
builddeps  :
    - pkgconfig(SDL_mixer)
    - pkgconfig(sdl)
setup      : |
    cd trunk
    %cmake -DLOAD_RESOURCES_FROM_FILES:BOOL=ON
build      : |
    cd trunk
    %make
install    : |
    install -Dm00755 trunk/bin/Bombermaaan $installdir/usr/share/Bombermaaan/bombermaaan
    install -dm00755 $installdir/usr/bin
    ln -sv ../share/Bombermaaan/bombermaaan $installdir/usr/bin/bombermaaan
    cp -r trunk/res/{images,sounds} $installdir/usr/share/Bombermaaan
    cp -r trunk/levels $installdir/usr/share/Bombermaaan
    install -Dm00644 $pkgfiles/bombermaaan.svg -t $installdir/usr/share/pixmaps
    install -Dm00644 $pkgfiles/bombermaaan.desktop -t $installdir/usr/share/applications
